version: "3"

services:
  gitlab:
    image: gitlab/gitlab-ce:12.1.4-ce.0
    container_name: gitlab
    hostname: "${HOSTNAME}"
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ${DATA_DIR}:/var/opt/gitlab
    ports:
      - "${SSH_PORT}:22"
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${MATTERMOST_PORT}:${MATTERMOST_PORT}"
      - "${REGISTRY_PORT}:${REGISTRY_PORT}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${EXTERNAL_HOSTNAME}:${HTTP_PORT}/'
        mattermost_external_url 'http://${EXTERNAL_HOSTNAME}:${MATTERMOST_PORT}/'
        registry_external_url 'http://${EXTERNAL_HOSTNAME}:${REGISTRY_PORT}/'
        gitlab_rails['gitlab_shell_ssh_port'] = ${SSH_PORT}
        gitlab_rails['gitlab_email_enabled'] = false
        gitlab_rails['time_zone'] = 'Asia/Tokyo'

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name : gitlab-runner
    hostname: gitlab-shared-runner
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config-runner:/etc/gitlab-runner

